### ISSUE TITLE
Anzeige der MAC-Adresse beim Einrichten

### ISSUE THREAD

**Issue by polygontwist** [merlinschumacher/Basecamp#10]
das als Anzeige wäre noch eine gute Option. Ich hab z.B. einen MAC-Filter im WLAN, da wär's hilfreich wenn man einfach dran kommt.
per Serielle:

>#include <WiFi.h>
>byte mac[6];
>...
> WiFi.macAddress(mac);
>  Serial.print("MAC: ");
>  Serial.print(mac[0],HEX);
>   Serial.print(":");
>   Serial.print(mac[1],HEX);
>   Serial.print(":");
>   Serial.print(mac[2],HEX);
>   Serial.print(":");
>   Serial.print(mac[3],HEX);
>   Serial.print(":");
>   Serial.print(mac[4],HEX);
>   Serial.print(":");
>   Serial.println(mac[5],HEX);

in der Oberfläche:

> WiFi.macAddress(mac);
>  String stringOne =  String(mac[0], HEX)+ ":" + String(mac[1], HEX)+ ":" + String(mac[2], HEX)+ ":"  + 
                      String(mac[3], HEX) + ":" + String(mac[4], HEX)+ ":" + String(mac[5], HEX); 
  iot.web.addInterfaceElement("", "p", "MAC= "+stringOne,"#wrapper");

Ich hab das so beim `void setup() {` drin, in der Basecamp Klasse ist die Schreibweise evtl. einfacher...

IP-Adresse ist ggf. auch in der Seriellen interessant.

**Comment by merlinschumacher** [comment]
Find ich ne gute Idee. Ein bisschen mehr Status-Output auf der seriellen Schnittstelle stand auch noch auf meinem Plan.
