### ISSUE TITLE
How is the data.hpp created?

### ISSUE THREAD

**Issue by T94T** [merlinschumacher/Basecamp#12]
Hi Merlin,
First of all: Really great and solid work! Thanks a lot for this project. 👍
Just bought the new c't magazine today 😄 
Question: How do you create the data.hpp? Why is the _logo_svg_gz_ not in use?

**Comment by polygontwist** [comment]
hi,
start the data2header.sh to make data.hpp

**Comment by T94T** [comment]
Cool, thanks! I didn't see the data2header.sh file. Is it really generating gzipped content?

**Comment by T94T** [comment]
Ok, I missed the _gzip *_ command. Closing now.
