### ISSUE TITLE
How to access config Variables.

### ISSUE THREAD

**Issue by markusb68** [merlinschumacher/Basecamp#25]
Hi,

i have added a config variable to the configuration web page:
`iot.mqtt.onConnect(onMqttConnect);`
`iot.web.addInterfaceElement("color", "input", "Defaultfarbe [#RRGGBB]:", "#configform", "LampColor");`
`iot.web.setInterfaceElementAttribute("color", "type", "text");`

Ho can I access this String "LampColor" in the setup() routine ?

**Comment by T94T** [comment]
`iot.configuration.get("LampColor");`
after
`iot.begin();`

**Comment by markusb68** [comment]
Thanks, works like a charm.
