### ISSUE TITLE
Nicht mehr kompatibel zu den ct-Projekten

### ISSUE THREAD

**Issue by veitk** [merlinschumacher/Basecamp#27]
Hallo, nur zur Info:

die ct-Projekte sind nicht mehr kompatibel (oder ich habs falsch ausgecheckt...) 

Die Methode configuration.getCString gibts nicht mehr, dachte man könnte es jetzt auf .get ändern ... da passt aber dann der Typ nicht mehr usw... für die interessierten Nachbastler nicht so schön.

**Comment by merlinschumacher** [comment]
Das wird im nächsten Release korrigiert.
