### ISSUE TITLE
Guru Meditation Error: Core  0 panic'ed (LoadProhibited)

### ISSUE THREAD

**Issue by J4nsen** [merlinschumacher/Basecamp#29]
Hallo, ich bekomme manchmal beim Aufwachen aus dem Deep-Sleep eine Exception. Er startet dann zwar neu, aber das sollte ja nicht passieren. Ich bin auf dem aktuellen Bootcamp master (f8ce5cdd5de785d9a372ef586f57f0018611a94d) und mit einem LOLIN32 unterwegs.

```
[...]
suspendESP: esp_deep_sleep_start()
ets Jun  8 2016 00:22:57

rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078a58

Basecamp V.0.1.6
Guru Meditation Error: Core  0 panic'ed (LoadProhibited)
. Exception was unhandled.
Register dump:
PC      : 0x400d2296  PS      : 0x00050030  A0      : 0x00000000  A1      : 0x3ffdf6a0  
A2      : 0x3ffd35b8  A3      : 0x411d9da6  A4      : 0x00000000  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x00000000  
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x00060023  A13     : 0x3ffcfd54  
A14     : 0x00000001  A15     : 0x00000001  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x400d2296:0x3ffdf6a0 0x7ffffffd:0x3ffdf710

Rebooting...
```

**Comment by merlinschumacher** [comment]
Hallo J4nsen,

der master ist nicht stabil. Nur die Releases sind getestet. Probieren Sie das mal mit dem letzten Release. Können Sie den Backtrace vielleicht mit dem [ESP-Exception-Decoder](https://github.com/me-no-dev/EspExceptionDecoder ) entschlüsseln, damit ersichtlich wird woran es hakt.

**Comment by merlinschumacher** [comment]
Besteht das Problem noch? Sonst würde ich den Issue schließen.

**Comment by J4nsen** [comment]
Ich hatte leider noch keine Zeit mich wieder dem Projekt zu widmen. Ich werde das Ticket aber nicht vergessen und mich dazu melden (in ca. ~2 Wochen).

**Comment by merlinschumacher** [comment]
Kein Problem. :+1:  Bis dann

**Comment by J4nsen** [comment]
Tritt mit v0.1.8 nicht auf. :)
Vielen Dank für das Projekt!

**Comment by merlinschumacher** [comment]
Danke!
