### ISSUE TITLE
Fehlermeldung beim Compilieren von ESP-Temp-Sensor.ino

### ISSUE THREAD

**Issue by ErichRa** [merlinschumacher/Basecamp#31]
Hallo Hr. Schumacher,

bekomme nach Installation aller notwendigen LIBs und dem Compilieren des Beispiels ESP-Temp-Sensor.ino folgende Fehlermeldung:

C:\Users\Erich\Documents\Arduino\libraries\Basecamp\Basecamp.cpp: In static member function 'static void Basecamp::OTAHandling(void*)':
C:\Users\Erich\Documents\Arduino\libraries\Basecamp\Basecamp.cpp:395:2: error: invalid use of 'void'

  .onEnd([]() {

  ^

Haben Sie einen Tipp an was es liegen kann?

Grüße
Erich Rauscher

**Comment by merlinschumacher** [comment]
Hallo Herr Rauscher,

welche Version von Basecamp haben Sie denn installiert? Mit der aktuellen Version 0.1.8 habe ich keiner Probleme beim Kompilieren des Beispiels. 

Mit besten Grüßen

Merlin Schumacher

**Comment by ErichRa** [comment]
Hallo Hr. Schumacher,

Das ging aber schnell...
Genau die 0.1.8 habe ich installiert.

Grüße 

Erich Rauscher

Von meinem iPad gesendet

**Comment by ErichRa** [comment]
Hallo Hr. Schumacher,

Kann es an Arduino-Version liegen? Benutze gerade 1.8.1.

Grüße Erich Rauscher

Von meinem iPad gesendet

**Comment by merlinschumacher** [comment]
Möglich wäre es. Kontrollieren Sie auch nochmal die Versionsstände des Arduino Core for ESP32 und der Abhängigkeiten von Basecamp.

**Comment by ErichRa** [comment]
Danke für den Hinweis.

Von meinem iPad gesendet

**Comment by ErichRa** [comment]
Habe den Fehler gefunden. Die Library ArduiniOTA.cpp und ArduinoOTA.h waren vom Stand 04.11.2017. 
Jetzt läuft es wie geplant. Arduino Version war nicht die Ursache, habe sie aber trotzdem aktualisiert.

Danke und Gruß Erich Rauscher

**Comment by merlinschumacher** [comment]
@ErichRa können Sie mir sagen, was Sie gemacht haben um das Problem zu beseitigen? Andere Anwender haben das Problem auch. Ich kann es aber nicht reproduzieren.

**Comment by merlinschumacher** [comment]
Vielen Dank!
