### ISSUE TITLE
OTA über Webserver (Beispiel)

### ISSUE THREAD

**Issue by helmar74** [merlinschumacher/Basecamp#38]
Hallo,

ich baue gerade den Doorsensor aus der ct nach. Ich würde den Sourcecode gerne um folgende Funktion erweitert:
Wenn der ESP durch die Setup Routine läuft soll er eine Prozedur aufrufen, in der er auf einem Webserver "nachschaut" ob dort ein Firmware (.bin Datei) liegt. Wenn die Datei vorhanden ist, soll er diese laden und ein Update durchführen.

Hat so was schon jemand implementiert und könnte man den Beispielcode haben?

Danke im voraus 

Helmar

**Comment by merlinschumacher** [comment]
Hallo Helmar,

hier finden Sie eine [Beispielimplementation](https://github.com/espressif/arduino-esp32/tree/master/libraries/Update/examples/AWS_S3_OTA_Update) des ESP32 Projekts für genau diesen Fall. 
Das Feature kommt vielleicht noch für Basecamp. Sie sind nicht der erste der danach fragt.

**Comment by helmar74** [comment]
Hallo,

danke für den Hinweis. Ich habe noch das hier gefunden, das '"kenne" ich schon vom 8266:
[https://github.com/suculent/esp32-http-update/blob/master/examples/httpUpdate/httpUpdate.ino](https://github.com/suculent/esp32-http-update/blob/master/examples/httpUpdate/httpUpdate.ino)

Gruss

Helmar
