### ISSUE TITLE
Parameter dem Konfig Webinterface hinzufügen

### ISSUE THREAD

**Issue by helmar74** [merlinschumacher/Basecamp#39]
Weiss jemand, wie man dem Türsensor Beispiel weitere Parameter im Webinterface hinzufügen kann (z.B. mehrere MQTT Topics) und wie man diese dann im Source Code abfragen/verwenden kann?

Gibt es irgendwo eine Doku zu Basecamp?

Danke im Voraus.

Helmar

**Comment by merlinschumacher** [comment]
Hallo Helmar,

an der Doku sitze ich noch.
Unter 
https://github.com/merlinschumacher/ESP-Temp-Sensor/blob/master/ESP-Temp-Sensor.ino
finden Sie ein Beispiel, dass das Web-Interface erweitert:

```
  iot.web.addInterfaceElement(
    "tempDisplay",
    "input",
    "Aktuelle Temperatur:",
    "#configform",
    "my-Temperature"
  );
  iot.web.setInterfaceElementAttribute(
    "tempDisplay",
    "readonly",
    "true"
);
```
