### ISSUE TITLE
1.configurationsaufruf klappt nicht mit ipad

### ISSUE THREAD

**Issue by polygontwist** [merlinschumacher/Basecamp#6]
mit einem ipad3 (altes) und einem alten Handy(Lumina mit windows8.1) habe ich probiert drauf zukommen:
-WLAN "ESP32" Verbindung hat geklappt
-im Webbrowser blieb nach http://192.168.4.1/ der Bildschirm weiß
-http://192.168.4.1/basecamp.css bzw. .js ließ sich aufrufen, der Inhalt war zu sehen

mein Basisscript:
`#define DEBUG 1
#include <Basecamp.hpp>

Basecamp iot;

void setup() {
  iot.begin();
}

void loop() {}`

Ausgaben in der Seriellen:

> O, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078ad0
Basecamp V.0.1.2
Factory reset was forced.
Rebooting.
ets Jun  8 2016 00:22:57

> rst:0xc
(SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078ad0
Basecamp V.0.1.2
Failed to open config file
Configuration empty

**Comment by polygontwist** [comment]
hab es jetzt mit einem Laptop versucht, damit ging es (Win10, chrome).

**Comment by polygontwist** [comment]
ich habe herausgefunden das `fetch(jsonData)` (basecamp.js) mit einem iPad IOS9.3 nicht funktioniert. Der Befehl ist zu neu für meine mobilen Geräte. https://caniuse.com/#search=fetch
Eine Lösung für ältere Geräte ist die Verwendung des klassischen new XMLHttpRequest(); Objektes.

**Comment by merlinschumacher** [comment]
Hey,

ich habe die JavaScript-Datei mal versucht mit dem iPad 3 zu debuggen. Nicht nur funktioniert fetch() nicht, sondern auch FormData und Default Parameter für JavaScript-Funktionen. 

Da das JavaScript möglichst klein bleiben soll, würde ich den Support außen vor lassen. Und dafür extra einen Polyfill einzubinden halte ich für Overkill.

**Comment by polygontwist** [comment]
hmm, Platz ist ja genug evtl. könnte man es dann noch minifizieren. Nun dann pick ich mir die interessanten Dinge raus (z.B. update über wlan). Ich lasse mir die Ansteuerung direkt am Gerät gerne auch für ältere Geräte offen. Wenn der Hauptserver ausfällt kann ich Rollo oder Licht immernoch befeuern.

**Comment by polygontwist** [comment]
hab heute die Neue Version getestet, danke für das Umschreiben - funktioniert auf meinem alten iPad3 perfekt!

**Comment by merlinschumacher** [comment]
Sehr gut! Gern geschehen.
