### ISSUE TITLE
MIME types

### ISSUE THREAD

**Issue by polygontwist** [merlinschumacher/Basecamp#9]
ist hier evtl. nicht so relevant: WebServer.cpp
server->on("/basecamp.js" ... müsste  "text/js" statt "text/css" sein
server->on("/data.json"  ... müsste  "application/json" statt "text/css" sein 

aber so wäre es schöner :-)

https://developer.mozilla.org/de/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

**Comment by merlinschumacher** [comment]
Ich hab das Problem gefixt. Die MIME types sollten nun stimmen. Nur den Aufruf der JSON-Datei bei abgeschlossener Konfiguration konnte ich nicht fixen, da die Webserver-Bibliothek da einen falschen MIME type sendet.
Dazu gibt es jetzt einen pull request:
[https://github.com/me-no-dev/ESPAsyncWebServer/pull/311](https://github.com/me-no-dev/ESPAsyncWebServer/pull/311)
